### ISSUE TITLE
Some avatars not showing up

### ISSUE THREAD

**Issue by jamiewilson** [bengott/meteor-avatar#37]
Hey there. Really appreciate all the work on this package. It's great! I've got a telescope-based app and am showing upvoter's avatars for each post, but it seems to only display the first and the last. Really strange:

![screen shot 2014-12-30 at 3 32 44 pm](https://cloud.githubusercontent.com/assets/3308673/5583143/987a61fe-9039-11e4-8b85-934a26b67153.png)

Yet, if I view my /all-users page, they all display correctly and then when I return to the post list, I can see them again.

![screen shot 2014-12-30 at 3 32 25 pm](https://cloud.githubusercontent.com/assets/3308673/5583157/bb09ad74-9039-11e4-8510-6c4b12913146.png)

Any ideas of what might be going on here? [My repo is here if you have a chance to look into it.](https://github.com/weld-co/telescope-theme-weld) It's probably something funky that I did, but am at a loss. Any help would be much appreciated. Thanks man

**Comment by bengott** [comment]
Hmm, I'm not sure... @SachaG actually wrote that code to show the small avatars for the participants/commenters, and if I remember correctly from the Slack chatroom, you're showing upvoters instead of commenters? Perhaps those userIds aren't being retrieved with the post subscription?

**Comment by SachaG** [comment]
That does sound like a subscription problem. 

Relevant thread: http://meta.telesc.pe/posts/y4piwYfDhzJMPpHdb

**Comment by jamiewilson** [comment]
Awesome. Thanks for the help guys!
