### ISSUE TITLE
Rendering issues (Slava's screencast)

### ISSUE THREAD

**Issue by SachaG** [bengott/meteor-avatar#47]
I've noticed this slow-down issue ever since using the avatar package in Telescope. Would be awesome to fix it!

https://www.youtube.com/watch?v=AkSoLAFXrvE

/cc @slava

**Comment by Slava** [comment]
After digging around, I think the whole Telescope codebase relies on `Meteor.user()` everywhere?

**Comment by bengott** [comment]
Thanks Sacha and Slava. Good teaching lesson for using [field specifiers](https://docs.meteor.com/#/full/fieldspecifiers), eh? And Telescope could probably use an overhaul too?

**Comment by SachaG** [comment]
Yeah definitely. This is something I completely overlooked. Probably worth
writing a blog post about it…

**Comment by Slava** [comment]
I mean, it is probably not a big deal. You never see someone constantly
updating the profile over and over again every 200ms.

**Comment by SachaG** [comment]
But I've certainly seen UI slowdowns since around the time we implemented
avatars. So it might be related.

**Comment by bengott** [comment]
Right.. Reactively reloading avatars every time something changes on the user object could get expensive. Other parts of the UI too, perhaps..
