### ISSUE TITLE
GitHub avatars should use https

### ISSUE THREAD

**Issue by jorisbontje** [bengott/meteor-avatar#48]
Requesting GitHub avatars using HTTP urls give an error (unless you run a plugin such as HTTPS Everywhere):
http://avatars.githubusercontent.com/jorisbontje?s=200

```
$ curl -v "http://avatars.githubusercontent.com/moncrey?s=200"
...
< HTTP/1.1 404 Not Found
```

The HTTPS urls work okay:
https://avatars.githubusercontent.com/jorisbontje?s=200

```
$ curl -v "https://avatars.githubusercontent.com/moncrey?s=200"
...
< HTTP/1.1 200 OK
```

**Comment by bengott** [comment]
Hmm, that's new. Looks there are issues regarding http/https retrieval of images from other linked services too.. (PRs #39 and #46)
