### ISSUE TITLE
Broken Avatars?

### ISSUE THREAD

**Issue by SachaG** [bengott/meteor-avatar#52]
Just testing out the latest version of the package, but it seems some avatars are a bit broken?

See http://meta.telesc.pe/

**Comment by MonkeyDo** [comment]
Well, as far as I am concerned, the problem came from a chrome extension, which didn't play nice with gravatar's servers.
Try to go to gravatar.com, and see if you have problems loading their css styles. If you do, try turning off extensions one by one until yo find the culprit.

**Comment by antiBaconMachine** [comment]
For me it was ghostery, just needed to allow each service.
