### ISSUE TITLE
Meteor 1.1: avatar-hide-initials CSS class is applied instead of avatar-hide-image

### ISSUE THREAD

**Issue by SachaG** [bengott/meteor-avatar#58]
On the Telescope homepage, avatars are getting the `avatar-hide-initials` class instead of `avatar-hide-image`.

For some reason they're working fine on post pages though. 

See: http://meta.telesc.pe/ vs http://meta.telesc.pe/posts/3hDwb4D9HQntws4ey

Also, it seems like this started happening with the recent 1.1 update.

**Comment by bengott** [comment]
Alright, I think the issue the same one we saw before.. expired twitter images. If a user changes his/her twitter profile pic, Telescope doesn't update the services.twitter.profile_image_url until the user logs out an logs back in...

**Comment by SachaG** [comment]
I'm not sure if that's it, as the issue is happening specifically for users who *didn't* log in via Twitter.

**Comment by bengott** [comment]
Yeah, you're right. After exploring some more, it's not just a twitter thing. I'm seeing the hide-initials class on gravatars that return 404, which shouldn't happen.

I'm gonna try to put some time in this weekend to do a revamp. Things are too fragile as it is.. I also think the package tries to be too smart, which makes the logic much more complicated than it needs to be.

**Comment by SachaG** [comment]
What if you just added `onerror="this.style.display='none';"` to the `img` tag?
