### ISSUE TITLE
defaultImageUrl: Relative path not working

### ISSUE THREAD

**Issue by neilyoung** [bengott/meteor-avatar#61]
Avatar.options = {
      fallbackType: "default image",
  	  defaultImageUrl: "img/avatar.png"
    };

renders to

GET http://i2.wp.com/localhost/img/avatar.png 404 (Not Found)

**Comment by neilyoung** [comment]
Maybe I've overseen this or you have added it right now:

   Note that Gravatar's default option requires a publicly accessible URL, so it won't work when your app is    running on localhost and you're using either the included package default image or a custom defaultImageUrl that is a relative path. It will work fine once deployed though.

But I can confirm: Works if loaded from remote

**Comment by bluebay** [comment]
This is really painful while development. Is there is any fix for this?

**Comment by GerryR** [comment]
You can try this https://github.com/bengott/meteor-avatar/pull/62
