### ISSUE TITLE
Random errors are showing initials instead of avatars

### ISSUE THREAD

**Issue by gdw2** [bengott/meteor-avatar#68]
I've got a page with several facebook avatars (all of the same user).  From refresh to refresh, I get different results.  Usually they all show up, or they all don't, but sometimes I get a mix.  In the debug tool's element browser, if I delete the SPAN associated with the initials, and remove the `display: none` property of the `<img>` tag, the image shows fine.   I'm not sure what's causing the `onerror` to trip.  I don't see any errors in the network tab of the debug tools.

Is this related to any currently-open issues?  Or a new issue?

**Comment by CarlQLange** [comment]
I've a PR in that solves this issue for me https://github.com/bengott/meteor-avatar/pull/67. I think the onerror fires because the images are loaded before the page has all the info it needs, then re-loaded reactively.

**Comment by rodrigok** [comment]
I think that the PR #69 is more appropriate to solve this problem

**Comment by gdw2** [comment]
https://github.com/bengott/meteor-avatar/pull/69 works for me!
