### ISSUE TITLE
Avatar only renders initials on mobile app

### ISSUE THREAD

**Issue by ecuanaso** [bengott/meteor-avatar#70]
When I run my app in my localmachine the avatar package picks up the users facebook and or google avatar, however when I run the app on my android phone, the avatar only picks up the initials of the user.  What could be the problem?

**Comment by zimme** [comment]
Newer versions of Meteor don't do `App.accessRule("*");` by default.

You need to add `.accessRule`'s for all the urls you wanna allow.

**Comment by ecuanaso** [comment]
I've added the accessrules and i still only get the initials on my mobile app.

this is my publish:
Meteor.publish('userData', function() {
  if(!this.userId) return null;
  return Meteor.users.find(this.userId, {fields: {
    "services.facebook.id" : true,
    "services.google.picture": true
  }});
});

this is my subscription:
  Deps.autorun(function () {
    this.subscription = Meteor.subscribe('userData', Meteor.userId());
  }.bind(this));

this is my avatar options :
Avatar.options = {
  fallbackType: 'default image',
  gravatarDefault: 'identicon'
};

**Comment by zimme** [comment]
I have no idea, hopefully someone else does.

**Comment by raiyankamal** [comment]
Hi @ecuanaso, have you looked in to the console log while your app is running on an android phone? If you are using the chrome browser, you can type ```chrome:inspect``` in the address bar to see a list of devices attached to your computer. From there you can open your device and check the console logs.

**Comment by raiyankamal** [comment]
I ran in to the same issue yesterday, interesting coincidence. From the inspector I saw that the app was getting 404 error from all the image sources. In my case, the problem was solved by adding access rules to each specific image source like this:

```javascript
App.accessRule("*.twimg.com"); // twitter
App.accessRule("*.facebook.com"); // facebook
App.accessRule("*.fbcdn.net"); // facebook
App.accessRule("fbcdn-profile-a.akamaihd.net:*"); // facebook
App.accessRule("*.gravatar.com:*"); // gravatar
App.accessRule("lh3.googleusercontent.com"); // g+
App.accessRule("*.licdn.com");``` // linkedin
