### ISSUE TITLE
Linked-in support

### ISSUE THREAD

**Issue by agnitin** [bengott/meteor-avatar#75]
Could you please also add linked-in support?

**Comment by raiyankamal** [comment]
I've already added LinkedIn support, and sent a pull request. It will be available when the admin decides to merge my pull request.
In the mean time you can use the package hosted in my repo. https://github.com/raiyankamal/meteor-avatar

**Comment by agnitin** [comment]
Hi Sacha,
Is there any easy way to use this package with Telescope?

Thanks in advance.

**Comment by raiyankamal** [comment]
Hi Sacha, thanks for merging the linkedin support. I just updated the Readme include some missing information regarding linkedin support. Please have a look and merge when you have time. Thanks again.

**Comment by SachaG** [comment]
@agnitin Telescope already uses this package, just not the latest version yet. 
@raiyankamal thanks!

**Comment by agnitin** [comment]
package name has been changed to utilities:avatar from bengott:avatar?

**Comment by raiyankamal** [comment]
Hi agnitin, you're right - the package name is now utilities:avatar. It is mentioned in the readme file, to install the package:
$ meteor add utilities:avatar

**Comment by SachaG** [comment]
Yes, @bengott stopped maintained the package so I took the initiative to change the name so it's not linked to a specific author anymore, and can be maintained by anybody who wants to take charge (that would be me currently, but I'm happy to pass the torch…)

**Comment by agnitin** [comment]
Sorry, I meant if I add this new package to Telescope and remove bengott:avatar, it does not seem to work. Think it maybe because the package name has changed.

**Comment by SachaG** [comment]
Telescope does not use bengott:avatar anymore, it aready uses
utilities:avatar
