### ISSUE TITLE
Default options for optional options

### ISSUE THREAD

**Issue by coniel** [bengott/meteor-avatar#76]
Is it possible to set default options in the configuration for things like shape, textColor, bgColor and size?

If not, would it be possible to add this ability? I want all of my avatars to be rounded, and have a specific text and background color, it's a bit of a pain (and not good if I want to change one of the values in the future) to add it every time the template is used.

**Comment by SachaG** [comment]
I think you should do this in CSS. Actually I'm not sure why those are even options, it seems like the kind of things you should put in your stylesheet.
