### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by SachaG** [bengott/meteor-avatar#79]
I emailed, Slack'd, and mentioned @bengott multiple times in the last couple months but haven't heard back from him a single time. In fact, I'm a bit worried that something might've happened to him. Or maybe he just decided to quit the tech industry altogether?

In the meantime, I've been trying take care of this package but I just don't have much free time since I already have to maintain Telescope. So I think it'd be great if somebody else was willing to maintain it moving forward. 

Since the package has already been renamed to `utilities:avatar` from `bengott:avatar`, a change of maintainer would not require any change on the end user's part (I would just give you access to the `utilities` organization). 

We would probably have to change repos though, which would mean losing the PRs and issues associated with this repo, which is why I haven't done it yet. 

Anyway, I'm curious to get your thoughts on this. 

@rodrigok @CarlQLange @GerryR @zimme @indymike @raiyankamal @TheAncientGoat @jorisbontje @em0ney @cwohlman @kevohagan

**Comment by em0ney** [comment]
I've done a pull request for this project before, would be happy to help.  Relatively time-poor for the next couple weeks but happy to help where I can.

**Comment by raiyankamal** [comment]
I can also pitch in from time to time.
If the open issues and PRs cannot be migrated to a new repo, the best alternative would be to resolve/close them before migrating to the new repo. I will contribute a couple of hours for next few days to go through the open issues. Hope that helps.

**Comment by zimme** [comment]
I have some "radical" ideas surrounding this package and when I have the time I'll discuss and submit PR's but there's a real possibility that it will end up as it's own package depending on the discussions with people using this package.

I'm sorry to say that I don't have the time to be an official maintainer of this project but I will happily try and help out as much as possible.

**Comment by SachaG** [comment]
@raiyankamal yeah that would help! It'd be great to sort out as many of them as we can before we move on.

**Comment by rodrigok** [comment]
Unfortunately we aren't using this package in Rocket.Chat anymore :(

**Comment by timothyarmes** [comment]
Hi,

I'd be happy to take over maintenance of this package if people are happy with that. I'd at last be able to merge in my changes!

Let me know at we can work out how to best go about it.

Tim

**Comment by SachaG** [comment]
@timothyarmes what's your Meteor Developer Account username?

**Comment by timothyarmes** [comment]
It's *tarmes*.

**Comment by dandv** [comment]
Does anyone here have maintainer rights to the package on Atmosphere? It would be great to publish an update to the README to advise users to go to the `utilities` package.

Otherwise, we can [flag the package](https://atmospherejs.com/bengott/avatar) and wait for the `utilities` one to gather stars.

**Comment by SachaG** [comment]
I have maintainer rights for https://atmospherejs.com/utilities/avatar, but not for https://atmospherejs.com/bengott/avatar (which is the reason why I created a new package in the first place). I agree we should flag `bengott:avatar`.
