### ISSUE TITLE
Rendering on the server side

### ISSUE THREAD

**Issue by sungwoncho** [bengott/meteor-avatar#82]
I would like to use `{{> avatar }}` while rendering templates in the server side. I am using [meteor-handlebars-server](https://github.com/cmather/meteor-handlebars-server).

When I try to render `myTemplate.handlebars` with avatar partial, I get:

    Error: The partial avatar could not be found

I tried to make `myTemplate.js` in the server directory like this:

```javascript
Handlebars.templates.myTemplate({}, {
  avatar: Handlebars.templates.avatar
});
```

But it didn't do anything. Any suggestions?

**Comment by guns2410** [comment]
+1
