### ISSUE TITLE
stylus version conflict

### ISSUE THREAD

**Issue by funston** [bengott/meteor-avatar#83]
not sure if this is Meteor or something. but it seems Meteor auto updated me, which sucks, as it seemed to have broken a bunch of things. can't find any workaround...but really like using the avatar packages.

While selecting package versions:
error: Conflict: Constraint stylus@1.0.5 || 1.0.7 is not satisfied by stylus 2.511.1.
Constraints on package "stylus":
- stylus@=2.511.1 <- top level
- stylus@1.0.5 || 1.0.7 <- bengott:avatar 0.7.6

**Comment by SachaG** [comment]
You should not be using `bengott:avatar`, but `utilities:avatar`. This package is not maintained anymore
