### ISSUE TITLE
Add upload functionality

### ISSUE THREAD

**Issue by bengott** [bengott/meteor-avatar#9]
I've had some preliminary success integrating [particle4dev:upload-avatar](https://atmospherejs.com/particle4dev/upload-avatar) into a test project. For this project, however, I would need to modify it a fair amount in order to achieve what I want. The method of saving the image directly on the user object as a base64-encoded string does work though.
@particle4dev: Would you be interested in collaborating/contributing on this?

@Kestanous had suggested using [vsivsi:file-collection](https://atmospherejs.com/vsivsi/file-collection), which is another file upload option. It has some other nice features like HTTP interfaces and resumable uploads too. Dunno if those features are explicitly necessary, but they might be nice to have.

Anyone have opinions on this?

**Comment by tedgoldstein** [comment]
Awesome package!  

One simple enhancement would be have a hook when images are not found and have the app provide the image URL.. Here is a little sketch:

Avatar.registerHook("ImageNotFound", function (userIdentifier) {
    .... look it up in vsivsi or collections 2 blobs or whatever
     return { imageUrl: imageUrl, ... any other parameters you need }
}

That way the storage of the image is left to the app to figure it out.

**Comment by shkomg** [comment]
I think, you may also look for the image src link in ```profile.avatar``` - this way project author may have avatar uploads done manually over CollectionFS or whatever he uses in his project.

I'd prefer this functionality. This is really simple & flexible solution.

@bengott what do you think?

**Comment by timothyarmes** [comment]
@shkomg I created a pull request ages ago to do that, but it's not been accepted for some reason.

**Comment by shkomg** [comment]
@timothyarmes sad to hear :( I'd love having that feature!

**Comment by dropfen** [comment]
Couldn't we just use cloudinary to store the uploaded images? So we don't need to host them and cloudinary gives you also a lot of features like crop, create thumbnails..

**Comment by shkomg** [comment]
+1
